### ISSUE TITLE
Message: Class 'Dotenv\Dotenv' not found

### ISSUE THREAD

**Issue by mikelgmh** [technoknol/env-in-CodeIgniter#2]
I used composer to get DotEnv. I followed the readme, but it says:

> An uncaught Exception was encountered
> Type: Error
> 
> Message: Class 'Dotenv\Dotenv' not found
> 
> Filename: C:\xampp\htdocs\shopCaseCodeigniter\application\libraries\Env.php
> 
> Line Number: 12

The Dotenv library has been installed to C:\xampp\htdocs\PROJECT_ROOT_FOLDER\vendor\vlucas\phpdotenv

¿How can I solve this issue?

**Comment by mikelgmh** [comment]
I did not import `require('../vendor/autoload.php');`.

**Comment by johnadan** [comment]
Hi @mikelgmh . What file did you declare the `require('../vendor/autoload.php');` ? Did you declare it on the same file?
